version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app_backend/app
    env_file:
      - .env.example # Will create this later for environment variables
